

SELECT APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT, PATIENT, DOCTOR
WHERE APPOINTMENT.PT_NO = PATIENT.PT_NO AND APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
AND DATEDIFF('2022-04-13', APNT_YMD) = 0 AND APNT_CNCL_YN = 'N' AND APPOINTMENT.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC